import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'todo-input',
  template: `
  <div class="todo-input">
  <input
  type="text"
  [value]="title"
  (keyup.enter)="changeTitle($event.target.value)"
  #inputElement>

  <button class="btn" (click)="changeTitle(inputElement.value)">Save</button>
  <p>The title is {{ title }}</p>
  </div>
  `,
  styleUrls: ['./input.component.css']
})
export class InputComponent implements OnInit {
  @Output() submit: EventEmitter<string> = new EventEmitter();
  title = 'Blah';

  constructor() {
    this.changeTitle('I love Angular');
  }

  ngOnInit() {
  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }

  changeTitle(newTitle: string): void {
    this.submit.emit(newTitle);
  }
}
